name: Build WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Build WASM
        run: |
          source emsdk/emsdk_env.sh
          cd wasm
          ./build.sh
      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: wasm/ 
