name: Build all WASM extensions
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Build AsuraScans
        run: |
          cd extensions/asurascans
          chmod +x build.sh
          ./build.sh

      - name: Build all WASM extensions
        run: |
          for ext in extensions/*; do
            if [ -d "$ext/src" ] && [ -f "$ext/src/build.sh" ]; then
              echo "Building $ext"
              cd "$ext/src"
              chmod +x build.sh
              ./build.sh
              cd ..
              # Переместить wasm в корень расширения
              if [ -f manga_parser.wasm ]; then
                mv manga_parser.wasm ../
              fi
              cd ../..
            fi
          done

      # - name: Build mangadex WASM
      #   run: |
      #     cd wasm_mangadex
      #     ./build.sh
      #     cp manga_parser.wasm ../extensions/mangadex/manga_parser.wasm

      - name: Commit WASM files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add extensions/*/asurascans_parser.wasm
          git commit -m "Update WASM parser" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
