name: Build WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "source $PWD/emsdk_env.sh" >> $GITHUB_ENV
      - name: Build WASM
        run: |
          source emsdk/emsdk_env.sh
          cd wasm
          ./build.sh
      - name: Upload WASM artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm
          path: wasm/


